# Generated by Django 4.2.2 on 2023-06-29 12:19

from django.db import migrations, models
import json_encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("items", models.JSONField(encoder=json_encoder.CustomJSONEncoder)),
                (
                    "full_details",
                    models.JSONField(encoder=json_encoder.CustomJSONEncoder),
                ),
            ],
        ),
    ]
